### ISSUE TITLE
no icon

### ISSUE THREAD

**Issue by promeneur** [mathiscode/password-leak-monitor#1]
Is it normal there is no icon anywhere to access the addon?

**Comment by mathiscode** [comment]
Yes, that's normal - at the moment, there are no options to be configured, so the addon just sits in the background and does its thing without any menus.

**Comment by promeneur** [comment]
it is a security helper addon.
perhaps an icon is usefull to signal the addon is ok. no?

**Comment by mathiscode** [comment]
Very good point! I'll work on that as soon as possible, or feel free to submit a PR!

**Comment by mathiscode** [comment]
@promeneur Just a quick update to let you know that the extension has been rewritten from scratch and now includes an icon, along with other features.

[Download v2.0.1](https://addons.mozilla.org/en-US/firefox/addon/password-leak-monitor/)

**Comment by promeneur** [comment]
thanks
